import { MoonrakerFile } from "../types.slint";
import { Filesystem, Utils } from "../state.slint";
import { ProgressIndicator, ScrollView, Button, Palette } from "std-widgets.slint";
import { Page } from "../components/page.slint";
import { Icons, Constants } from "../constants.slint";
import { VerticalScrollable, VerticalStretch } from "../components/vertical.slint";
import { HorizontalStretch } from "../components/horizontal.slint";

export component File inherits Rectangle 
{
    in property <MoonrakerFile> file;
    callback on_file_selected();

    TouchArea {
        clicked => { root.on_file_selected(); }
    }
    HorizontalStretch {
        spacing: Constants.spacing-half;
        
        Image {
            source: Utils.image_exists(file.thumbnail) ? file.thumbnail : Icons.file;
            colorize: Utils.image_exists(file.thumbnail) ? transparent : Palette.foreground;
            vertical-alignment: center;
            horizontal-alignment: center;
            width: Constants.thumbnail-size;
            height: Constants.thumbnail-size;
        }
        Text { 
            text: file.path; 
            horizontal-stretch: 1; 
            vertical-alignment: center; 
            overflow: elide; 
        }
        Text { 
            text: file.filament-type != "" 
                ? file.filament_type + " - " + Utils.time_in_seconds_to_string(file.estimated-time-s) 
                : Utils.time_in_seconds_to_string(file.estimated-time-s); 
            horizontal-alignment: right; 
            vertical-alignment: center; 
        }
    }
}

export component FileListPage inherits Page 
{
    header: "Files";

    property <MoonrakerFile> selected_file;
    property <int> thumbnail_index: 0;

    init() => {
        Filesystem.list_files();
    }

    if Filesystem.loading: ProgressIndicator {
        indeterminate: true;
        width: 66%;
    }

    if !Filesystem.loading && selected_file.path == "": VerticalScrollable {
        for f in Filesystem.files: File {
            file: f;
            on_file_selected => { root.selected_file = f; }
        }
    }

    if selected_file.path != "": Rectangle {
        height: 100%;
        width: 100%;

        VerticalStretch {
            Text { text: "File: " + selected_file.path; font-weight: 900; overflow: elide; }
            Text { text: "Size: " + Utils.format_bytes(selected_file.size); }
            Text { text: "Modified: " + selected_file.modified; }
            Text { text: "Permissions: " + selected_file.permissions; }
            Button { text: "Close"; clicked => { root.selected_file = {}; thumbnail_index += 1; } }
        }
    }
}