import { Page } from "../components/page.slint";
import { ScrollView } from "std-widgets.slint";
import { QuickActions } from "../state.slint";
import { Icons, Constants } from "../constants.slint";
import { Palette, StyleMetrics } from "std-widgets.slint";
import { SmallButton } from "../components/small-button.slint";
import { VerticalScrollable } from "../components/vertical.slint";
import { HorizontalStretch } from "../components/horizontal.slint";

component QuickAction inherits Rectangle
{
    in property <string> quick-action;
    width: 100%;

    HorizontalStretch {
        Image {
            source: Icons.action;
            colorize: Palette.foreground;
            width: Constants.thumbnail-size;
            height: Constants.thumbnail-size;
        }

        Text { 
            text: quick-action; 
            horizontal-stretch: 1; 
            vertical-alignment: center; 
            overflow: elide; 
        }

        SmallButton {
            text: "Run";
            width: 50px;
            vertical-stretch: 1;
            border-radius: Constants.radius-md;
            clicked => { QuickActions.execute_quick_action(quick-action); }
        }
    }
}

export component QuickActionsPage inherits Page 
{
    header: "Quick Actions";

    // TODO: Power devices

    VerticalScrollable {
        for quick-action in QuickActions.quick-actions: QuickAction { 
            quick-action: quick-action; 
        }
    }

    if QuickActions.quick-actions.length <= 0: Rectangle {
        Text {
            text: "No quick actions found!\n\nPlease refer to the configuration reference\nto set this up!";
            vertical-alignment: center;
            horizontal-alignment: center;
        }
    }
}