import { Palette } from "std-widgets.slint";
import { DisplayStatus } from "../state.slint";

export component BottomBar inherits Rectangle {
    height: 20px;
    width: 100%;
    background: Palette.alternate-background;
    in property <string> text;

    Text {
        text: text;
        horizontal-alignment: center;
        vertical-alignment: bottom;
        color: Palette.alternate-foreground;
    }
}

export component BottomBarWithStatusMessage inherits BottomBar {
    text: DisplayStatus.message;
    height: DisplayStatus.message == "" ? 0px : 20px;
}