import { Palette } from "std-widgets.slint";
import { Constants } from "../constants.slint";

export component GhostButton inherits Rectangle {
    in property <string> text;
    in property <color> text-color: Palette.foreground;
    callback clicked;

    states [
        pressed when touch-area.pressed : {
            root.background: Palette.selection-background;
        }
    ]

    min-height: t.height * 2;
    min-width: t.width * 1.5;
    border-radius: Constants.radius-md;
    //background: red;

    t := Text {
        text: text;
        color: text-color;
        font-weight: 600;
    }

    touch-area := TouchArea {
        clicked => { root.clicked(); }
    }
}