import { Palette } from "std-widgets.slint";

export component GhostButton inherits VerticalLayout {
    in property <string> text;
    in property <color> text-color: Palette.foreground;
    callback clicked;

    states [
        pressed when touch-area.pressed : {
            container.background: Palette.selection-background;
        }
    ]

    container := Rectangle {
        min-height: t.height * 2;
        min-width: t.width * 1.5;
        border-radius: 10px;
        //background: red;

        t := Text {
            text: text;
            color: text-color;
            font-weight: 600;
        }

        touch-area := TouchArea {
            clicked => { root.clicked(); }
        }
    }
}