import { StyleMetrics } from "std-widgets.slint";
import { Constants } from "../constants.slint";

export component Page inherits Rectangle {
    in property <string> header;
    width: 100%; 
    height: 100%;
    GridLayout {
        padding-top: Constants.padding-half;
        padding-bottom: Constants.padding-half;
        padding-left: Constants.padding;
        padding-right: Constants.padding;
        Rectangle {
            vertical-stretch: 1;
            @children
        }
    }
}