import { GhostButton } from "ghost-button.slint";
import { Palette, StyleMetrics } from "std-widgets.slint";
import { Constants } from "../constants.slint";
import { VerticalStretch } from "vertical.slint";
import { HorizontalEnd } from "horizontal.slint";

export component YesNoPrompt inherits Rectangle 
{
    in property <string> title <=> title_text.text;
    in property <string> message;

    callback yes();
    callback no();
    border-radius: Constants.radius-xl;
    background: Palette.background;

    VerticalStretch {
        padding: Constants.padding-extra; 

        title_text := Text {
            color: Palette.foreground;
            font-size: Constants.font-size-lg;
            font-weight: 600;
        }

        if message != "": title_message := Text {
            text: message;
            color: Palette.foreground;
            wrap: word-wrap;
        }

        Rectangle {}

        HorizontalEnd {            
            GhostButton {
                text: "No";
                width: 60px;
                text-color: Palette.accent-background;
                clicked => { root.no(); }
            }

            GhostButton {
                text: "Yes";
                width: 60px;
                text-color: Palette.accent-background;
                clicked => { root.yes(); }
            }
        }
    }
}