[display.default]
width = 480
height = 272

[moonraker]
host = "localhost"
port = 7125

[heater_presets]
extruder = [ 200, 240, 280 ]
heater_bed = [ 60, 70 ]

[ui]
dark_mode = true
left_sidebar = ["files", "temperature", "move", "emergency_stop"]
right_sidebar = ["fan", "macros", "console", "settings"]

[quick_actions]
Restart = ["RESTART"]
"Firmware Restart" = ["FIRMWARE_RESTART"]
Home = ["G28"]