// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { StyleMetrics } from "std-widgets.slint";
export global Icons {
    out property <image> arrow-up: @image-url("assets/arrow-up.svg");
    out property <image> arrow-left: @image-url("assets/arrow-left.svg");
    out property <image> arrow-right: @image-url("assets/arrow-right.svg");
    out property <image> chevron-left: @image-url("assets/chevron-left.svg");
    out property <image> arrow-down: @image-url("assets/arrow-down.svg");
    out property <image> arrow-circle-o-left: @image-url("assets/arrow-circle-o-left.svg");
    out property <image> globe: @image-url("assets/globe.svg");
    out property <image> expand-more: @image-url("assets/expand-more.svg");
    out property <image> backspace: @image-url("assets/backspace.svg");
    out property <image> bed: @image-url("assets/bed.svg");
    out property <image> check: @image-url("assets/check.svg");
    out property <image> close: @image-url("assets/close.svg");
    out property <image> console: @image-url("assets/console.svg");
    out property <image> device_temperature: @image-url("assets/device_temperature.svg");
    out property <image> eject: @image-url("assets/eject.svg");
    out property <image> emergency_stop: @image-url("assets/emergency.svg");
    out property <image> extruder: @image-url("assets/extruder.svg");
    out property <image> fan: @image-url("assets/fan.svg");
    out property <image> file: @image-url("assets/file.svg");
    out property <image> move: @image-url("assets/move.svg");
    out property <image> print: @image-url("assets/print.svg");
    out property <image> quick_action: @image-url("assets/quickaction.svg");
    out property <image> settings: @image-url("assets/settings.svg");
    out property <image> temperature: @image-url("assets/temperature.svg");
    out property <image> action: @image-url("assets/action.svg");
    out property <image> power-device: @image-url("assets/power_device.svg");
}

export global Constants {
    out property <int> font-weight-bold: 900;
    out property <int> font-weight-thin: 300;

    out property <length> font-size-sm: 10px;
    out property <length> font-size-lg: 20px;

    out property <length> radius-sm: 6px;
    out property <length> radius-md: 10px;
    out property <length> radius-lg: 16px;
    out property <length> radius-xl: 24px;

    out property <length> padding-extra: StyleMetrics.layout-padding * 1.5;
    out property <length> padding: StyleMetrics.layout-padding;
    out property <length> padding-half: StyleMetrics.layout-padding / 2;

    out property <length> spacing: StyleMetrics.layout-spacing;
    out property <length> spacing-half: StyleMetrics.layout-spacing / 2;

    out property <length> thumbnail-size: 32px;
    out property <length> list-entry-height: 32px;
}