// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

export global Icons {
    out property <image> arrow-up: @image-url("assets/arrow-up.svg");
    out property <image> arrow-left: @image-url("assets/arrow-left.svg");
    out property <image> arrow-right: @image-url("assets/arrow-right.svg");
    out property <image> chevron-left: @image-url("assets/chevron-left.svg");
    out property <image> arrow-down: @image-url("assets/arrow-down.svg");
    out property <image> arrow-circle-o-left: @image-url("assets/arrow-circle-o-left.svg");
    out property <image> globe: @image-url("assets/globe.svg");
    out property <image> expand-more: @image-url("assets/expand-more.svg");
    out property <image> backspace: @image-url("assets/backspace.svg");
    out property <image> bed: @image-url("assets/bed.svg");
    out property <image> check: @image-url("assets/check.svg");
    out property <image> close: @image-url("assets/close.svg");
    out property <image> console: @image-url("assets/console.svg");
    out property <image> device_temperature: @image-url("assets/device_temperature.svg");
    out property <image> eject: @image-url("assets/eject.svg");
    out property <image> emergency_stop: @image-url("assets/emergency.svg");
    out property <image> extruder: @image-url("assets/extruder.svg");
    out property <image> fan: @image-url("assets/fan.svg");
    out property <image> file: @image-url("assets/file.svg");
    out property <image> move: @image-url("assets/move.svg");
    out property <image> print: @image-url("assets/print.svg");
    out property <image> quick_action: @image-url("assets/quickaction.svg");
    out property <image> settings: @image-url("assets/settings.svg");
    out property <image> temperature: @image-url("assets/temperature.svg");
    out property <image> action: @image-url("assets/action.svg");
}
