import { StyleMetrics } from "std-widgets.slint";

export global Icons {
    out property <image> arrow-up: @image-url("assets/arrow-up.png");
    out property <image> arrow-left: @image-url("assets/arrow-left.png");
    out property <image> arrow-right: @image-url("assets/arrow-right.png");
    out property <image> chevron-left: @image-url("assets/chevron-left.png");
    out property <image> arrow-down: @image-url("assets/arrow-down.png");
    out property <image> arrow-circle-o-left: @image-url("assets/arrow-circle-o-left.png");
    out property <image> globe: @image-url("assets/globe.png");
    out property <image> expand-more: @image-url("assets/expand-more.png");
    out property <image> backspace: @image-url("assets/backspace.png");
    out property <image> bed: @image-url("assets/bed.png");
    out property <image> check: @image-url("assets/check.png");
    out property <image> close: @image-url("assets/close.png");
    out property <image> console: @image-url("assets/console.png");
    out property <image> device_temperature: @image-url("assets/device_temperature.png");
    out property <image> eject: @image-url("assets/eject.png");
    out property <image> emergency_stop: @image-url("assets/emergency.png");
    out property <image> extruder: @image-url("assets/extruder.png");
    out property <image> fan: @image-url("assets/fan.png");
    out property <image> file: @image-url("assets/file.png");
    out property <image> move: @image-url("assets/move.png");
    out property <image> print: @image-url("assets/print.png");
    out property <image> quick_action: @image-url("assets/quickaction.png");
    out property <image> settings: @image-url("assets/settings.png");
    out property <image> temperature: @image-url("assets/temperature.png");
    out property <image> action: @image-url("assets/action.png");
    out property <image> power-device: @image-url("assets/power_device.png");
    out property <image> height: @image-url("assets/height.png");
    out property <image> layer-height: @image-url("assets/layer_height.png");
    out property <image> start: @image-url("assets/play.png");
    out property <image> pause: @image-url("assets/pause.png");
    out property <image> stop: @image-url("assets/stop.png");
}

export global Constants {
    out property <int> font-weight-bold: 900;
    out property <int> font-weight-thin: 300;

    out property <length> font-size-sm: 10px;
    out property <length> font-size-md: 16px;
    out property <length> font-size-lg: 20px;

    out property <length> radius-sm: 6px;
    out property <length> radius-md: 10px;
    out property <length> radius-lg: 16px;
    out property <length> radius-xl: 24px;

    out property <length> padding-extra: StyleMetrics.layout-padding * 1.5;
    out property <length> padding: StyleMetrics.layout-padding;
    out property <length> padding-half: StyleMetrics.layout-padding / 2;
    out property <length> padding-quarter: StyleMetrics.layout-padding / 4;

    out property <length> spacing: StyleMetrics.layout-spacing;
    out property <length> spacing-half: StyleMetrics.layout-spacing / 2;

    out property <length> thumbnail-size: 32px;
    out property <length> list-entry-height: 32px;
}