import { ProgressIndicator, Button, StyleMetrics, Palette, ScrollView, Slider } from "std-widgets.slint";
import { VirtualKeyboardButton } from "virtual_keyboard.slint";
import "../AdwaitaSans-Regular.ttf";
import { TemperatureSensors, Heater } from "state.slint";
export * from "state.slint";

component Page inherits Rectangle {
    in property <string> header <=> h.text;
    width: 100%; 
    height: 100%;

    VerticalLayout {
        width: 100%;
        height: 100%;
        HorizontalLayout { 
            x: 10px;
            h := Text {
                font-weight: 900;
                horizontal-alignment: left;
                y: 10px;
            }
            padding-bottom: 20px;
            vertical-stretch: 0;
        }

        Rectangle {
            vertical-stretch: 1;
            @children
        }
    }
}

component PageOne inherits Page {
    header: "This is page 1";

    Rectangle {

        //Text { text: "This is page 2"; }
        ProgressIndicator {
            indeterminate: true;
            width: 200px;
        }
    }
}

component PageTwo inherits Page {
    header: "This is page 2";

    VerticalLayout {
        Text {
            text: "Hello!";
        }
        Rectangle {
            background: #ff0000;
        }
        Rectangle {
            background: #00ff00;
        }
        Rectangle {
            background: #0000ff;
        }
    }
}

component PageThree inherits Page {
    header: "This is page 3";

    ScrollView {
        VerticalLayout {
            for t in [ "Hello", "World", "!", "!", "!", "!", "!", "!", "hello atom", ":)", "why", "does", "this", "have", "to", "be", "so", "long?", "a", "b", "c" ] : Text {
                text: t;
            }
            Rectangle {
                background: #ff0000;
                height: 100px;
            }
            Rectangle {
                background: #00ff00;
                height: 100px;
            }
            Rectangle {
                background: #0000ff;
                height: 100px;
            }
        }
    }

}

component IconButton inherits Rectangle {
    in property <image> icon <=> img.source;
    in property <bool> checked: false;
    in property <bool> left-side: true;
    in property <brush> foreground: checked ? Palette.accent-foreground : Palette.foreground;

    callback clicked();

    background: checked ? Palette.accent-background : Palette.background;
    border-top-left-radius: left-side ? StyleMetrics.layout-padding : 0;
    border-bottom-left-radius: left-side ? StyleMetrics.layout-padding : 0;
    border-top-right-radius: left-side ? 0 : StyleMetrics.layout-padding;
    border-bottom-right-radius: left-side ? 0 : StyleMetrics.layout-padding;

    img := Image {
        horizontal-alignment: center;
        vertical-alignment: center;
        colorize: foreground;
    }

    TouchArea {
        clicked => { root.clicked(); }
    }
}

component TopBar inherits Rectangle {
    height: 20px;
    width: 100%;
    background: Palette.alternate-background;

    HorizontalLayout {
        padding-top: 2px;
        padding-left: 10px;
        padding-right: 10px;
        spacing: 10px;
        Text {
            text: "Printer: Idle";
            color: Palette.alternate-foreground;
            font-weight: 900;
            horizontal-stretch: 0;
        }

        Rectangle {
            horizontal-stretch: 1;
        }

        HorizontalLayout {
            Image {
                source: @image-url("assets/extruder.svg");
                colorize: Palette.alternate-foreground;
            }
            Text {
                text: TemperatureSensors.extruder.target > 0
                    ? TemperatureSensors.extruder.temperature + "°C / " + TemperatureSensors.extruder.target + "°C"
                    : TemperatureSensors.extruder.temperature + "°C";
                color: Palette.alternate-foreground;
                font-weight: 900;
            }
        }
        
        if TemperatureSensors.heated_bed.name != "": HorizontalLayout {
            Image {
                source: @image-url("assets/bed.svg");
                colorize: Palette.alternate-foreground;
            }
            Text {
                text: TemperatureSensors.heated_bed.target > 0
                    ? TemperatureSensors.heated_bed.temperature + "°C / " + TemperatureSensors.heated_bed.target + "°C"
                    : TemperatureSensors.heated_bed.temperature + "°C";
                color: Palette.alternate-foreground;
                font-weight: 900;
            }
        }

    }
}


export struct MoonrakerFileTest
{
    path: string,
    modified: float,
    size: int,
    permissions: string,
    thumbnail: image,
}

export global AppState
{
    in-out property <bool> moonraker_connected: false;
    in-out property <string> klipper_state: "-";
    in-out property <string> klipper_state_message: "-";
}

export global Filesystem 
{
    callback list_files();
    callback download_thumbnail(index : int);
    in-out property <[MoonrakerFileTest]> files: [{
        path: "example.gcode", modified: 123456.0, size: 12345, permissions: "rw-r--r--",
    }, {
        path: "a-really-really-really-really-really-really-really-really-really-long-name.gcode", modified: 123456.0, size: 12345, permissions: "rw-r--r--"
    }];
    in-out property <bool> loading: false;
}

export global Utils
{
    pure callback image_exists(image: image) -> bool;  
    pure callback format_bytes(size: int) -> string;
    pure callback prettify_name(name: string) -> string;
}

component FileListView inherits Rectangle 
{
    property <MoonrakerFileTest> selected_file;
    property <int> thumbnail_index: 0;

    init() => {
        Filesystem.list_files();
    }

    if Filesystem.loading: ProgressIndicator {
        indeterminate: true;
        width: 200px;
    }

    if !Filesystem.loading && selected_file.path == "": ScrollView {
        VerticalLayout {
            for f in Filesystem.files: VerticalLayout {
                height: 40px;
                width: 100%;
                Rectangle {
                    TouchArea {
                        clicked => { root.selected_file = f; }
                    }
                    HorizontalLayout {
                        spacing: 10px;
                        padding: 5px;
                        Image {
                            source: Utils.image_exists(f.thumbnail) ? f.thumbnail : @image-url("assets/file.svg");
                            colorize: Utils.image_exists(f.thumbnail) ? transparent : Palette.foreground;
                            vertical-alignment: center;
                            horizontal-alignment: center;
                            width: 32px;
                        }
                        Text { text: f.path; horizontal-stretch: 1; vertical-alignment: center; overflow: elide; }
                        Text { text: Utils.format_bytes(f.size); horizontal-alignment: right; vertical-alignment: center; }
                    }
                }
                Rectangle { height: 1px; background: Palette.border; horizontal-stretch: 1; width: 100%; }
            }
        }
    }

    if selected_file.path != "": Rectangle {
        height: 100%;
        width: 100%;

        VerticalLayout {
            Text { text: "File: " + selected_file.path; font-weight: 900; overflow: elide; }
            Text { text: "Size: " + Utils.format_bytes(selected_file.size); }
            Text { text: "Modified: " + selected_file.modified; }
            Text { text: "Permissions: " + selected_file.permissions; }
            Button { text: "Close"; clicked => { root.selected_file = {}; Filesystem.download_thumbnail(thumbnail_index); thumbnail_index += 1; } }
        }
    }
}

component SmallButton inherits Rectangle {
    in property <string> text;
    callback clicked();

    background: Palette.control-background;
    border-radius: 20px;

    states [
        pressed when touch-area.pressed : {
            state-area.opacity: 0.5;
        }
    ]

    GridLayout {
        padding-left: 10px;
        padding-right: 10px;
    
        Rectangle {
            touch-area := TouchArea {
                clicked => { root.clicked(); }
            }

            Text {
                text: root.text;
                color: Palette.control-foreground;
                horizontal-alignment: center;
                vertical-alignment: center;
                font-size: 12px;
            }
        }
    }

    state-area := Rectangle {
        border-radius: root.border-radius;
        opacity: 0;
        background: #000000;

        animate opacity { duration: 30ms; }
    }
}

component InteractableTemperatureElement {
    in-out property <Heater> heater;
    property <int> target: heater.target;
    property <string> friendly_name: Utils.prettify_name(heater.name);

    changed heater => {
        target = heater.target;
    }

    callback on_manual_entry(internal_name: string, friendly_name: string);

    VerticalLayout {
        HorizontalLayout {
            height: 40px;
            spacing: 10px;

            Image {
                colorize: Palette.foreground;
                source: heater.name == "extruder"
                    ? @image-url("assets/extruder.svg")
                    : heater.name == "heater_bed"
                        ? @image-url("assets/bed.svg")
                        : @image-url("assets/fan.svg"); // TODO: Do temp sensor
            }

            Text {
                text: friendly_name;
                horizontal-stretch: 1;
                vertical-alignment: center;
                overflow: elide;
            }

            Text {
                text: target > 0
                    ? heater.temperature + "°C -> " + target + "°C"
                    : heater.temperature + "°C";
                vertical-alignment: center;
                font-weight: 900;
            }
        }
        HorizontalLayout {
            spacing: 10px;
            height: 40px;
            padding-bottom: 10px;
            SmallButton {
                text: "Off";
                clicked => { 
                    TemperatureSensors.set_new_target_temperature(heater.name, 0);
                }   
            }
            for preset in heater.presets : SmallButton {
                text: preset + "°C";
                clicked => { 
                    TemperatureSensors.set_new_target_temperature(heater.name, preset);
                }   
            }
            SmallButton {
                text: "Set";
                clicked => { 
                    on_manual_entry(heater.name, friendly_name);
                }
            }
        }
        Rectangle { height: 1px; background: Palette.border; horizontal-stretch: 1; width: 100%; }
    }
}

component NumberPad inherits Rectangle 
{
    in property <string> name;
    callback accept(number: int);
    callback cancel();
    property <int> current-number: 0;

    function add(key: int) {
        if (current-number > 1000) {
            return;
        }

        current-number = current-number * 10 + key;        
    }

    function remove() {
        current-number = floor(current-number / 10);
    }

    VerticalLayout {
        spacing: 5px;
        
        HorizontalLayout {
            spacing: 5px;
            vertical-stretch: 1;
            
            Text {
                text: name + ": " + current-number;
                horizontal-alignment: center;
                vertical-alignment: center;
                font-size: 20px;
                font-weight: 900;
                horizontal-stretch: 5;
            }

            VirtualKeyboardButton { icon: @image-url("assets/backspace.svg"); key-pressed => { remove(); } horizontal-stretch: 1; }
        }

        HorizontalLayout {
            spacing: 5px;
            vertical-stretch: 1;
            VirtualKeyboardButton { key: "1"; key-pressed => { add(1) } }
            VirtualKeyboardButton { key: "2"; key-pressed => { add(2) } }
            VirtualKeyboardButton { key: "3"; key-pressed => { add(3) } }
            VirtualKeyboardButton { icon: @image-url("assets/check.svg"); key-pressed => { accept(current-number); current-number = 0; } }
        }

        HorizontalLayout {
            spacing: 5px;
            vertical-stretch: 1;
            VirtualKeyboardButton { key: "4"; key-pressed => { add(4) } }
            VirtualKeyboardButton { key: "5"; key-pressed => { add(5) } }
            VirtualKeyboardButton { key: "6"; key-pressed => { add(6) } }
            VirtualKeyboardButton { icon: @image-url("assets/close.svg"); key-pressed => { cancel(); } }
        }

        HorizontalLayout {
            spacing: 5px;
            vertical-stretch: 1;
            VirtualKeyboardButton { key: "7"; key-pressed => { add(7) } }
            VirtualKeyboardButton { key: "8"; key-pressed => { add(8) } }
            VirtualKeyboardButton { key: "9"; key-pressed => { add(9) } }
            VirtualKeyboardButton { key: "0"; key-pressed => { add(0) } }
        }
    }
}

component TemperaturePage inherits Page {
    header: "Temperature";
    property <bool> is_keyboard_open: false;
    property <string> internal_temp_device_name;
    property <string> friendly_temp_device_name;

    if is_keyboard_open: GridLayout {
        padding-left: StyleMetrics.layout-padding / 2;
        padding-right: StyleMetrics.layout-padding / 2;
        NumberPad {
            name: friendly_temp_device_name;
            accept(number) => {
                TemperatureSensors.set_new_target_temperature(internal_temp_device_name, number);
                is_keyboard_open = false;
            }
            cancel() => {
                is_keyboard_open = false;
            }
        }
    }

    function open_keyboard(internal_name: string, friendly_name: string) {
        internal_temp_device_name = internal_name;
        friendly_temp_device_name = friendly_name;
        is_keyboard_open = true;
    }

    ScrollView {
        VerticalLayout {
            padding-left: 20px;
            padding-right: 20px;
            InteractableTemperatureElement { heater: TemperatureSensors.extruder; on_manual_entry(internal-name, friendly-name) => { open_keyboard(internal-name, friendly-name); }  }
            if TemperatureSensors.heated_bed.name != "": InteractableTemperatureElement { heater: TemperatureSensors.heated_bed; on_manual_entry(internal-name, friendly-name) => { open_keyboard(internal-name, friendly-name); }}
            for temp_fan in TemperatureSensors.heater_fans: InteractableTemperatureElement { heater: temp_fan.heater;on_manual_entry(internal-name, friendly-name) => { open_keyboard(internal-name, friendly-name); } }
        }

        visible: !is_keyboard_open;
    }
}

component PageFour inherits Page {
    header: "Files";

    FileListView {
        width: 100%;
        height: 100%;
    }
}

component BottomBar inherits Rectangle {
    height: 20px;
    width: 100%;
    background: Palette.alternate-background;

    HorizontalLayout {
        Text {
            text: "Elegoo is pirating Klipper. Release the source code! https://freethecode.lol/";
            horizontal-alignment: center;
            vertical-alignment: center;
            color: Palette.alternate-foreground;
        }
    }
}

component MainView
{
    in-out property <int> current-page: 0;

    VerticalLayout { 
        TopBar {

        }

        HorizontalLayout {
            VerticalLayout {
                spacing: 5px;
                horizontal-stretch: 0;
                min-width: 50px;
                IconButton { icon: @image-url("assets/print.svg"); checked: root.current-page == 0; clicked => { root.current-page = 0; } }
                IconButton { icon: @image-url("assets/temperature.svg"); checked: root.current-page == 1; clicked => { root.current-page = 1; } }
                IconButton { icon: @image-url("assets/move.svg"); checked: root.current-page == 2; clicked => { root.current-page = 2; } }
                IconButton { icon: @image-url("assets/emergency.svg"); checked: root.current-page == 3; clicked => { root.current-page = 3;  } foreground: red; }
            }

            Rectangle { 
                horizontal-stretch: 1;

                //PageOne { visible: root.current-page == 0;  }
                //PageTwo { visible: root.current-page == 1;  }
                PageThree { visible: root.current-page == 2;  }
                if root.current-page == 1: TemperaturePage { }
                if root.current-page == 0: PageFour { }
            }

            VerticalLayout {
                spacing: 5px;
                horizontal-stretch: 0;
                min-width: 50px;
                IconButton { icon: @image-url("assets/fan.svg"); checked: root.current-page == 4; clicked => { root.current-page = 4; } left-side: false; }
                IconButton { icon: @image-url("assets/quickaction.svg"); checked: root.current-page == 5; clicked => { root.current-page = 5; } left-side: false; }
                IconButton { icon: @image-url("assets/console.svg"); checked: root.current-page == 6; clicked => { root.current-page = 6; } left-side: false; }
                IconButton { icon: @image-url("assets/settings.svg"); checked: root.current-page == 7; clicked => { root.current-page = 7; } left-side: false; }
            }
        }

        BottomBar {

        }
    }
}

export component AppWindow inherits Window {
    width: 480px;
    height: 272px;

    // The buttons to switch pages

    default-font-family: "Adwaita Sans";

    if AppState.moonraker_connected && AppState.klipper_state == "Ready" : MainView {
        width: 100%;
        height: 100%;
    }

    if AppState.moonraker_connected && AppState.klipper_state != "Ready" && AppState.klipper_state != "" : VerticalLayout {
        width: 100%;
        spacing: 20px;
        Rectangle {}
        Rectangle {
            VerticalLayout { 
                width: 70%;
                spacing: 20px;
                alignment: center;
                Text {
                    text: AppState.klipper_state;
                    font-weight: 900;
                    horizontal-alignment: center;
                }
                Text {
                    text: AppState.klipper_state_message;
                    horizontal-alignment: center;
                }
                if AppState.klipper_state == "Error" || AppState.klipper_state == "Shutdown": HorizontalLayout {
                    spacing: 20px;
                    Button {
                        text: "Restart";
                        clicked => { }
                    }
                    Button {
                        text: "Firmware Restart";
                        clicked => { }
                    }
                }
            } 
        }
        Rectangle {}
    }

    if !AppState.moonraker_connected || AppState.klipper_state == "": VerticalLayout
    {
        VerticalLayout {
            width: 100%;
            spacing: 20px;
            Rectangle {

            }
            Rectangle {
                VerticalLayout { 
                    width: 200px;
                    spacing: 20px;
                    alignment: center;
                    Text {
                        text: "Connecting to moonraker...";
                        horizontal-alignment: center;
                    }
                    ProgressIndicator {
                        width: 100%;
                        indeterminate: true;
                    }
                } 
            }
            Rectangle {

            }
        }
    }

/*
    keyboard := VirtualKeyboard {
        y: parent.height - self.height;
    }
*/
    /*
    VerticalLayout {
        HorizontalLayout {
            Button { text: "Page 1"; clicked => { root.current-page = 0; } checked: root.current-page == 0; icon: @image-url("assets/print.svg"); }
            Button { text: "Page 2"; clicked => { root.current-page = 1; } checked: root.current-page == 1; }
            Button { text: "Page 3"; clicked => { root.current-page = 2; } checked: root.current-page == 2;}
            
        }

        Rectangle { 
            PageOne { visible: root.current-page == 0;  }
        }
    }
    */
}