import { ProgressIndicator, Button, StyleMetrics, Palette, ScrollView, Slider, ComboBox, TabWidget } from "std-widgets.slint";
import { VirtualKeyboardButton } from "virtual_keyboard.slint";
import "../AdwaitaSans-Regular.ttf";
import { TemperatureSensors, DisplayStatus, PrinterAdministration, GcodeCommands, Filesystem, Utils, Webhooks, UiSettings } from "state.slint";
import { Heater, TemperatureSensor, MoonrakerFile } from "types.slint";
import { Icons } from "constants.slint";
import { Page } from "components/page.slint";
import { InteractableTemperatureElement, TemperaturePage } from "pages/temperature-page.slint";
import { SmallButton } from "components/small-button.slint";
import { IconButton, LeftSideIconButton, RightSideIconButton } from "components/icon-button.slint";
import { TemperatureEntry } from "components/number-pad.slint";
import { TopBar } from "components/top-bar.slint";
import { FileListPage } from "pages/file-list-page.slint";
import { BottomBarWithStatusMessage } from "components/bottom-bar.slint";
import { YesNoPrompt } from "components/yes-no-prompt.slint";
import { QuickActionsPage } from "pages/quick-actions-page.slint";
import { VerticalStretch, VerticalCenter } from "components/vertical.slint";
export * from "state.slint";

component MainView inherits Rectangle
{
    in-out property <int> current-page: 0;
    property <bool> is_emergency_prompt_open: false;
    background: Palette.alternate-background;

    VerticalLayout { 
        TopBar {

        }

        HorizontalLayout {
            if UiSettings.left-sidebar.length > 0: VerticalStretch {
                width: 50px;
                spacing: 0;

                for component in UiSettings.left-sidebar: LeftSideIconButton {
                    icon: UiSettings.id-to-image[component];
                    checked: root.current-page == component;
                    clicked => { 
                        if (component == 3) { 
                            is_emergency_prompt_open = true;
                        } else {
                            current-page = component;
                        }
                    }
                    foreground: component == 3 
                        ? red
                        : root.current-page == component 
                            ? Palette.accent-foreground 
                            : Palette.foreground;
                }
            }

            Rectangle { 
                horizontal-stretch: 1;
                background: Palette.background;
                border-top-left-radius: StyleMetrics.layout-padding / 2;
                border-top-right-radius: StyleMetrics.layout-padding / 2;
                border-bottom-left-radius: DisplayStatus.message == "" ? 0 : StyleMetrics.layout-padding / 2;
                border-bottom-right-radius: DisplayStatus.message == "" ? 0 : StyleMetrics.layout-padding / 2;
                
                if root.current-page == 1: TemperaturePage {}
                if root.current-page == 0: FileListPage  {}
                if root.current-page == 5: QuickActionsPage {}
            }

            if UiSettings.right-sidebar.length > 0: VerticalStretch {
                width: 50px;
                spacing: 0;

                for component in UiSettings.right-sidebar: RightSideIconButton {
                    icon: UiSettings.id-to-image[component];
                    checked: root.current-page == component;
                    clicked => { 
                        if (component == 3) { 
                            is_emergency_prompt_open = true;
                        } else {
                            current-page = component;
                        }
                    }
                    foreground: component == 3 
                        ? red
                        : root.current-page == component 
                            ? Palette.accent-foreground 
                            : Palette.foreground;
                }
            }
        }

        BottomBarWithStatusMessage { }
    }

    // TODO: Split this into a component
    if is_emergency_prompt_open: Rectangle 
    {
        background: #00000080;
        TouchArea { }

        VerticalCenter {
            width: 60%;

            YesNoPrompt {
                title: "Emergency Stop";
                message: "Are you sure you want to perform an emergency stop?";
                yes() => {
                    is_emergency_prompt_open = false;
                    PrinterAdministration.emergency_stop();
                }
                no() => {
                    is_emergency_prompt_open = false;
                }
            }
        }
    }
}

export component AppWindow inherits Window {
    default-font-family: "Adwaita Sans";

    if Webhooks.moonraker_connected && Webhooks.klipper_state == "Ready" : MainView {
        width: 100%;
        height: 100%;
    }

    if Webhooks.moonraker_connected && Webhooks.klipper_state != "Ready" && Webhooks.klipper_state != "" : VerticalLayout {
        width: 100%;
        spacing: 20px;
        Rectangle {}
        Rectangle {
            VerticalLayout { 
                width: 70%;
                spacing: 20px;
                alignment: center;
                Text {
                    text: Webhooks.klipper_state;
                    font-weight: 900;
                    horizontal-alignment: center;
                }
                Text {
                    text: Webhooks.klipper_state_message;
                    horizontal-alignment: center;
                }
                if Webhooks.klipper_state == "Error" || Webhooks.klipper_state == "Shutdown": HorizontalLayout {
                    spacing: 20px;
                    Button {
                        text: "Restart";
                        clicked => { PrinterAdministration.restart(); }
                    }
                    Button {
                        text: "Firmware Restart";
                        clicked => { PrinterAdministration.firmware_restart(); }
                    }
                }
            } 
        }
        Rectangle {}
    }

    if !Webhooks.moonraker_connected || Webhooks.klipper_state == "": VerticalLayout
    {
        VerticalLayout {
            width: 100%;
            spacing: 20px;
            Rectangle {

            }
            Rectangle {
                VerticalLayout { 
                    width: 200px;
                    spacing: 20px;
                    alignment: center;
                    Text {
                        text: "Connecting to moonraker...";
                        horizontal-alignment: center;
                    }
                    ProgressIndicator {
                        width: 100%;
                        indeterminate: true;
                    }
                } 
            }
            Rectangle {

            }
        }
    }
}