export struct TemperatureSensor
{
    name: string,
    temperature: int,
}

export struct Heater 
{
    name: string,
    temperature: int,
    target: int,
    presets: [int]
}

export struct HeaterFan
{
    speed: float,
    heater: Heater,
}

export struct MoonrakerFile
{
    path: string,
    modified: float,
    size: int,
    permissions: string,
    thumbnail: image,
    filament_used_gram: float,
    filament_type: string,
    height_mm: float,
    estimated_time_s: float,
    layer_height_mm: float,
    nozzle_diameter_mm: float,
}

export struct PowerDevice
{
    device: string,
    status: string,
    locked_while_printing: bool,
    device_type: string,
}